// ============================================================
// AUTO-GENERATED by ui_compiler.py  -- DO NOT EDIT
// Source: ui/screens/gallery_viewbustup.json
// ============================================================
#pragma once

#include "ui_types.h"

namespace ui_data_gallery_viewbustup {

    // Background
    constexpr const char* BG_IMAGE_ID = "still_viewbustup";
    constexpr int BG_SCROLL_X = 0;
    constexpr int BG_SCROLL_Y = 0;

    // Sprites
    constexpr int SPRITE_COUNT = 0;
    constexpr ui_types::SpriteEntry* SPRITES = nullptr;

    // Texts
    constexpr int TEXT_COUNT = 0;
    constexpr ui_types::TextEntry* TEXTS = nullptr;

    constexpr ui_types::ScreenData SCREEN = {
        BG_IMAGE_ID, BG_SCROLL_X, BG_SCROLL_Y,
        SPRITE_COUNT, SPRITES,
        TEXT_COUNT, TEXTS
    };

} // namespace ui_data_gallery_viewbustup
