// ============================================================
// AUTO-GENERATED by ui_compiler.py  -- DO NOT EDIT
// Source: ui/screens/gallerymenu.json
// ============================================================
#pragma once

#include "ui_types.h"

namespace ui_data_gallerymenu {

    // Background
    constexpr const char* BG_IMAGE_ID = "still_gallerymenu";
    constexpr int BG_SCROLL_X = 0;
    constexpr int BG_SCROLL_Y = 0;

    // Sprites
    constexpr int SPRITE_COUNT = 0;
    constexpr ui_types::SpriteEntry* SPRITES = nullptr;

    // Texts
    constexpr int TEXT_COUNT = 2;
    constexpr ui_types::TextEntry TEXTS[TEXT_COUNT] = {
        { "title", "GALLERY", 0.0f, -8.0f, true, false, 30, true },
        { "subtitle", "Coming Soon...", 0.0f, 8.0f, true, false, 30, true },
    };

    constexpr ui_types::ScreenData SCREEN = {
        BG_IMAGE_ID, BG_SCROLL_X, BG_SCROLL_Y,
        SPRITE_COUNT, SPRITES,
        TEXT_COUNT, TEXTS
    };

} // namespace ui_data_gallerymenu
