// ============================================================
// AUTO-GENERATED by ui_compiler.py  -- DO NOT EDIT
// Source: ui/screens/mainmenu.json
// ============================================================
#pragma once

#include "ui_types.h"

namespace ui_data_mainmenu {

    // Background
    constexpr const char* BG_IMAGE_ID = "still_mainmenu";
    constexpr int BG_SCROLL_X = 0;
    constexpr int BG_SCROLL_Y = 0;

    // Sprites
    constexpr int SPRITE_COUNT = 0;
    constexpr ui_types::SpriteEntry* SPRITES = nullptr;

    // Texts
    constexpr int TEXT_COUNT = 6;
    constexpr ui_types::TextEntry TEXTS[TEXT_COUNT] = {
        { "menu_0", "", 0.0f, -32.0f, true, false, 30, true },
        { "menu_1", "", 0.0f, -14.0f, true, false, 30, true },
        { "menu_2", "", 0.0f, 4.0f, true, false, 30, true },
        { "menu_3", "", 0.0f, 22.0f, true, false, 30, true },
        { "menu_4", "", 0.0f, 40.0f, true, false, 30, true },
        { "title_text", "ｽﾋﾟｷとマヨの倉庫番", 0.0f, -56.0f, true, false, 30, true },
    };

    constexpr ui_types::ScreenData SCREEN = {
        BG_IMAGE_ID, BG_SCROLL_X, BG_SCROLL_Y,
        SPRITE_COUNT, SPRITES,
        TEXT_COUNT, TEXTS
    };

} // namespace ui_data_mainmenu
