// ============================================================
// AUTO-GENERATED by ui_compiler.py  -- DO NOT EDIT
// Source: ui/screens/title.json
// ============================================================
#pragma once

#include "ui_types.h"

namespace ui_data_title {

    // Background
    constexpr const char* BG_IMAGE_ID = "bg_title_main";
    constexpr int BG_SCROLL_X = 0;
    constexpr int BG_SCROLL_Y = 0;

    // Sprites
    constexpr int SPRITE_COUNT = 1;
    constexpr ui_types::SpriteEntry SPRITES[SPRITE_COUNT] = {
        { "new_sprite", "ui_common", 0, 8.0f, -16.0f, true },
    };

    // Texts
    constexpr int TEXT_COUNT = 0;
    constexpr ui_types::TextEntry* TEXTS = nullptr;

    constexpr ui_types::ScreenData SCREEN = {
        BG_IMAGE_ID, BG_SCROLL_X, BG_SCROLL_Y,
        SPRITE_COUNT, SPRITES,
        TEXT_COUNT, TEXTS
    };

} // namespace ui_data_title
