// ============================================================
// AUTO-GENERATED by ui_compiler.py  -- DO NOT EDIT
// Source: ui/screens/sokoban_main.json
// ============================================================
#pragma once

#include "ui_types.h"

namespace ui_data_sokoban_main {

    // Background
    constexpr const char* BG_IMAGE_ID = "still_sokoban_main";
    constexpr int BG_SCROLL_X = 0;
    constexpr int BG_SCROLL_Y = 0;

    // Sprites
    constexpr int SPRITE_COUNT = 0;
    constexpr ui_types::SpriteEntry* SPRITES = nullptr;

    // Texts
    constexpr int TEXT_COUNT = 8;
    constexpr ui_types::TextEntry TEXTS[TEXT_COUNT] = {
        { "moves_text", "", -80.0f, 68.0f, true, false, 30, true },
        { "stage_text", "", 80.0f, 68.0f, true, false, 30, true },
        { "clear_text", "", 0.0f, -16.0f, true, false, 30, true },
        { "start_text", "", 0.0f, 0.0f, true, false, 30, true },
        { "endless_score_label", "", 0.0f, -24.0f, true, false, 30, true },
        { "endless_best_label", "", 0.0f, -4.0f, true, false, 30, true },
        { "endless_new_record", "", 0.0f, 16.0f, true, false, 30, true },
        { "endless_press_a", "", 0.0f, 40.0f, true, false, 30, true },
    };

    constexpr ui_types::ScreenData SCREEN = {
        BG_IMAGE_ID, BG_SCROLL_X, BG_SCROLL_Y,
        SPRITE_COUNT, SPRITES,
        TEXT_COUNT, TEXTS
    };

} // namespace ui_data_sokoban_main
