// ============================================================
// AUTO-GENERATED by ui_compiler.py  -- DO NOT EDIT
// Source: ui/screens/event.json
// ============================================================
#pragma once

#include "ui_types.h"

namespace ui_data_event {

    // Background
    constexpr const char* BG_IMAGE_ID = "gba_event";
    constexpr int BG_SCROLL_X = 0;
    constexpr int BG_SCROLL_Y = 0;

    // Sprites
    constexpr int SPRITE_COUNT = 4;
    constexpr ui_types::SpriteEntry SPRITES[SPRITE_COUNT] = {
        { "event_cg", "dummy", 0, 0.0f, -20.0f, 0.0f, false },
        { "char_left", "chara_portraits", 0, -60.0f, 0.0f, 0.0f, false },
        { "char_right", "chara_portraits", 3, 60.0f, 0.0f, 0.0f, false },
        { "msg_window", "ui_paper", 0, 0.0f, 50.0f, 0.0f, true },
    };

    // Texts
    constexpr int TEXT_COUNT = 2;
    constexpr ui_types::TextEntry TEXTS[TEXT_COUNT] = {
        { "name_box", "", -100.0f, 20.0f, ui_types::TextAlign::CENTER, 1.0f, false, 30, true },
        { "message_text", "", -110.0f, 40.0f, ui_types::TextAlign::CENTER, 1.0f, false, 30, true },
    };

    // Animations
    constexpr int ANIM_PRESET_COUNT = 0;
    constexpr ui_types::AnimPreset* ANIM_PRESETS = nullptr;

    constexpr int ANIM_ENTRY_COUNT = 0;
    constexpr ui_types::AnimEntry* ANIM_ENTRIES = nullptr;

    constexpr ui_types::ScreenData SCREEN = {
        BG_IMAGE_ID, BG_SCROLL_X, BG_SCROLL_Y,
        SPRITE_COUNT, SPRITES,
        TEXT_COUNT, TEXTS,
        ANIM_PRESET_COUNT, ANIM_PRESETS,
        ANIM_ENTRY_COUNT, ANIM_ENTRIES
    };

} // namespace ui_data_event
