// ============================================================
// AUTO-GENERATED by ui_compiler.py  -- DO NOT EDIT
// Source: ui/screens/sokoban_main.json
// ============================================================
#pragma once

#include "ui_types.h"

namespace ui_data_sokoban_main {

    // Background
    constexpr const char* BG_IMAGE_ID = "still_sokoban_main";
    constexpr int BG_SCROLL_X = 0;
    constexpr int BG_SCROLL_Y = 0;

    // Sprites
    constexpr int SPRITE_COUNT = 1;
    constexpr ui_types::SpriteEntry SPRITES[SPRITE_COUNT] = {
        { "rival_portrait", "chara_portraits", 0, 92.0f, -44.0f, 0.0f, true },
    };

    // Texts
    constexpr int TEXT_COUNT = 8;
    constexpr ui_types::TextEntry TEXTS[TEXT_COUNT] = {
        { "moves_text", "", -80.0f, 68.0f, ui_types::TextAlign::CENTER, 1.0f, false, 30, true },
        { "stage_text", "", 80.0f, 68.0f, ui_types::TextAlign::CENTER, 1.0f, false, 30, true },
        { "clear_text", "", 0.0f, -16.0f, ui_types::TextAlign::CENTER, 1.0f, false, 30, false },
        { "start_text", "", 0.0f, 0.0f, ui_types::TextAlign::CENTER, 1.0f, false, 30, false },
        { "endless_score_label", "", 0.0f, -24.0f, ui_types::TextAlign::CENTER, 1.0f, false, 30, false },
        { "endless_best_label", "", 0.0f, -4.0f, ui_types::TextAlign::CENTER, 1.0f, false, 30, false },
        { "endless_new_record", "", 0.0f, 16.0f, ui_types::TextAlign::CENTER, 1.0f, false, 30, false },
        { "endless_press_a", "", 0.0f, 40.0f, ui_types::TextAlign::CENTER, 1.0f, false, 30, false },
    };

    // Animations
    constexpr int ANIM_PRESET_COUNT = 0;
    constexpr ui_types::AnimPreset* ANIM_PRESETS = nullptr;

    constexpr int ANIM_ENTRY_COUNT = 0;
    constexpr ui_types::AnimEntry* ANIM_ENTRIES = nullptr;

    constexpr ui_types::ScreenData SCREEN = {
        BG_IMAGE_ID, BG_SCROLL_X, BG_SCROLL_Y,
        SPRITE_COUNT, SPRITES,
        TEXT_COUNT, TEXTS,
        ANIM_PRESET_COUNT, ANIM_PRESETS,
        ANIM_ENTRY_COUNT, ANIM_ENTRIES
    };

} // namespace ui_data_sokoban_main
