// ============================================================
// AUTO-GENERATED by ui_compiler.py  -- DO NOT EDIT
// Source: ui/screens/gallery_viewstill.json
// ============================================================
#pragma once

#include "ui_types.h"

namespace ui_data_gallery_viewstill {

    // Background
    constexpr const char* BG_IMAGE_ID = "still_viewstill";
    constexpr int BG_SCROLL_X = 0;
    constexpr int BG_SCROLL_Y = 0;

    // Sprites
    constexpr int SPRITE_COUNT = 0;
    constexpr ui_types::SpriteEntry* SPRITES = nullptr;

    // Texts
    constexpr int TEXT_COUNT = 0;
    constexpr ui_types::TextEntry* TEXTS = nullptr;

    // Animations
    constexpr int ANIM_PRESET_COUNT = 0;
    constexpr ui_types::AnimPreset* ANIM_PRESETS = nullptr;

    constexpr int ANIM_ENTRY_COUNT = 0;
    constexpr ui_types::AnimEntry* ANIM_ENTRIES = nullptr;

    constexpr ui_types::ScreenData SCREEN = {
        BG_IMAGE_ID, BG_SCROLL_X, BG_SCROLL_Y,
        SPRITE_COUNT, SPRITES,
        TEXT_COUNT, TEXTS,
        ANIM_PRESET_COUNT, ANIM_PRESETS,
        ANIM_ENTRY_COUNT, ANIM_ENTRIES
    };

} // namespace ui_data_gallery_viewstill
