// ============================================================
// AUTO-GENERATED by ui_compiler.py  -- DO NOT EDIT
// Source: ui/screens/settings.json
// ============================================================
#pragma once

#include "ui_types.h"

namespace ui_data_settings {

    // Background
    constexpr const char* BG_IMAGE_ID = "still_mainmenu";
    constexpr int BG_SCROLL_X = 0;
    constexpr int BG_SCROLL_Y = 0;

    // Sprites
    constexpr int SPRITE_COUNT = 0;
    constexpr ui_types::SpriteEntry* SPRITES = nullptr;

    // Texts
    constexpr int TEXT_COUNT = 5;
    constexpr ui_types::TextEntry TEXTS[TEXT_COUNT] = {
        { "title_text", "SETTINGS", 0.0f, -40.0f, true, false, 30, true },
        { "setting_0", "", 0.0f, -16.0f, true, false, 30, true },
        { "setting_1", "", 0.0f, 4.0f, true, false, 30, true },
        { "setting_2", "", 0.0f, 24.0f, true, false, 30, true },
        { "nav_text", "B:BACK", 0.0f, 56.0f, true, false, 30, true },
    };

    constexpr ui_types::ScreenData SCREEN = {
        BG_IMAGE_ID, BG_SCROLL_X, BG_SCROLL_Y,
        SPRITE_COUNT, SPRITES,
        TEXT_COUNT, TEXTS
    };

} // namespace ui_data_settings
