// ============================================================
// AUTO-GENERATED by ui_compiler.py  -- DO NOT EDIT
// Source: ui/screens/title.json
// ============================================================
#pragma once

#include "ui_types.h"

namespace ui_data_title {

    // Background
    constexpr const char* BG_IMAGE_ID = "bg_title";
    constexpr int BG_SCROLL_X = 0;
    constexpr int BG_SCROLL_Y = 0;

    // Sprites
    constexpr int SPRITE_COUNT = 0;
    constexpr ui_types::SpriteEntry* SPRITES = nullptr;

    // Texts
    constexpr int TEXT_COUNT = 1;
    constexpr ui_types::TextEntry TEXTS[TEXT_COUNT] = {
        { "press_start", "PRESS START", 0, 48, true, true, 30, true },
    };

    constexpr ui_types::ScreenData SCREEN = {
        BG_IMAGE_ID, BG_SCROLL_X, BG_SCROLL_Y,
        SPRITE_COUNT, SPRITES,
        TEXT_COUNT, TEXTS
    };

} // namespace ui_data_title
