// ============================================================
// AUTO-GENERATED by ui_compiler.py  -- DO NOT EDIT
// Source: ui/screens/save_select.json
// ============================================================
#pragma once

#include "ui_types.h"

namespace ui_data_save_select {

    // Background
    constexpr const char* BG_IMAGE_ID = "";
    constexpr int BG_SCROLL_X = 0;
    constexpr int BG_SCROLL_Y = 0;

    // Sprites
    constexpr int SPRITE_COUNT = 0;
    constexpr ui_types::SpriteEntry* SPRITES = nullptr;

    // Texts
    constexpr int TEXT_COUNT = 2;
    constexpr ui_types::TextEntry TEXTS[TEXT_COUNT] = {
        { "title_label", "セーブデータを選んでください", 0, -56, true, false, 0, true },
        { "hint_label", "A: 選択  B: タイトルへ", 0, 60, true, false, 0, true },
    };

    constexpr ui_types::ScreenData SCREEN = {
        BG_IMAGE_ID, BG_SCROLL_X, BG_SCROLL_Y,
        SPRITE_COUNT, SPRITES,
        TEXT_COUNT, TEXTS
    };

} // namespace ui_data_save_select
