#!/usr/bin/env python3
import json
import os
import sys

SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
SCREENS_DIR  = os.path.join(PROJECT_ROOT, "ui", "screens")
INCLUDE_DIR  = os.path.join(PROJECT_ROOT, "include")

def sanitize_id(s: str) -> str:
    return s.replace("-", "_").replace(" ", "_").upper()

def cpp_string(s: str) -> str:
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'

def compile_screen(json_path: str) -> str:
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    screen_name = data.get("screen", "unknown")
    ns          = f"ui_data_{screen_name}"

    bg_id = ""
    sprites = []
    texts = []

    # Flatten the tree
    def traverse(node, current_x, current_y):
        nonlocal bg_id
        if not node: return
        
        # accumulate
        nx = current_x + float(node.get("x", 0.0))
        ny = current_y + float(node.get("y", 0.0))
        
        ntype = node.get("type", "")
        if ntype == "bg":
            bg_id = node.get("image_id", "")
        elif ntype == "sprite":
            sprites.append({
                "id": node.get("id", "spr"),
                "image_set": node.get("image_set", ""),
                "image_no": int(node.get("image_no", 0)),
                "x": nx, "y": ny, "visible": True
            })
        elif ntype == "text":
            texts.append({
                "id": node.get("id", "txt"),
                "text": node.get("text", ""),
                "x": nx, "y": ny,
                "blink": node.get("blink", False),
                "visible": True
            })
            
        for child in node.get("children", []):
            traverse(child, nx, ny)

    traverse(data.get("root"), 0.0, 0.0)

    lines = []
    lines.append(f"// ============================================================")
    lines.append(f"// AUTO-GENERATED by ui_compiler.py  -- DO NOT EDIT")
    lines.append(f"// Source: ui/screens/{screen_name}.json")
    lines.append(f"// ============================================================")
    lines.append(f"#pragma once")
    lines.append(f"")
    lines.append(f"#include \"ui_types.h\"")
    lines.append(f"")
    lines.append(f"namespace {ns} {{")
    lines.append(f"")

    lines.append(f"    // Background")
    lines.append(f"    constexpr const char* BG_IMAGE_ID = {cpp_string(bg_id)};")
    lines.append(f"    constexpr int BG_SCROLL_X = 0;")
    lines.append(f"    constexpr int BG_SCROLL_Y = 0;")
    lines.append(f"")

    lines.append(f"    // Sprites")
    lines.append(f"    constexpr int SPRITE_COUNT = {len(sprites)};")
    if sprites:
        lines.append(f"    constexpr ui_types::SpriteEntry SPRITES[SPRITE_COUNT] = {{")
        for spr in sprites:
            lines.append(
                f"        {{ {cpp_string(spr.get('id',''))}, "
                f"{cpp_string(spr.get('image_set',''))}, "
                f"{spr['image_no']}, "
                f"{spr['x']}f, {spr['y']}f, "
                f"{'true' if spr.get('visible', True) else 'false'} }},"
            )
        lines.append(f"    }};")
    else:
        lines.append(f"    constexpr ui_types::SpriteEntry* SPRITES = nullptr;")
    lines.append(f"")

    lines.append(f"    // Texts")
    lines.append(f"    constexpr int TEXT_COUNT = {len(texts)};")
    if texts:
        lines.append(f"    constexpr ui_types::TextEntry TEXTS[TEXT_COUNT] = {{")
        for t in texts:
            lines.append(
                f"        {{ {cpp_string(t.get('id',''))}, "
                f"{cpp_string(t.get('text',''))}, "
                f"{t['x']}f, {t['y']}f, "
                f"true, "  # center align defaults to true for now
                f"{'true' if t.get('blink', False) else 'false'}, "
                f"30, " # blink interval
                f"{'true' if t.get('visible', True) else 'false'} }},"
            )
        lines.append(f"    }};")
    else:
        lines.append(f"    constexpr ui_types::TextEntry* TEXTS = nullptr;")
    lines.append(f"")

    lines.append(f"    constexpr ui_types::ScreenData SCREEN = {{")
    lines.append(f"        BG_IMAGE_ID, BG_SCROLL_X, BG_SCROLL_Y,")
    lines.append(f"        SPRITE_COUNT, SPRITES,")
    lines.append(f"        TEXT_COUNT, TEXTS")
    lines.append(f"    }};")
    lines.append(f"")
    lines.append(f"}} // namespace {ns}")
    lines.append(f"")

    return "\n".join(lines)


def main():
    if not os.path.isdir(SCREENS_DIR):
        print(f"[ui_compiler] Warning: screens dir not found: {SCREENS_DIR}", file=sys.stderr)
        return

    os.makedirs(INCLUDE_DIR, exist_ok=True)

    compiled = 0
    for fname in os.listdir(SCREENS_DIR):
        if not fname.endswith(".json"):
            continue
        json_path = os.path.join(SCREENS_DIR, fname)
        screen_name = fname[:-5]
        out_path = os.path.join(INCLUDE_DIR, f"ui_data_{screen_name}.h")

        cpp_src = compile_screen(json_path)

        existing = ""
        if os.path.exists(out_path):
            with open(out_path, "r", encoding="utf-8") as f:
                existing = f.read()

        if existing != cpp_src:
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(cpp_src)
            print(f"[ui_compiler] Generated: {out_path}")
        else:
            print(f"[ui_compiler] Up-to-date: {out_path}")

        compiled += 1

    print(f"[ui_compiler] Done: {compiled} screen(s) processed.")

if __name__ == "__main__":
    main()
