#!/usr/bin/env python3
import json
import os
import sys

SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
SCREENS_DIR  = os.path.join(PROJECT_ROOT, "ui", "screens")
INCLUDE_DIR  = os.path.join(PROJECT_ROOT, "include")

def sanitize_id(s: str) -> str:
    return s.replace("-", "_").replace(" ", "_").upper()

def cpp_string(s: str) -> str:
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'

def compile_screen(json_path: str) -> str:
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    screen_name = data.get("screen", "unknown")
    ns          = f"ui_data_{screen_name}"

    lines = []
    lines.append(f"// ============================================================")
    lines.append(f"// AUTO-GENERATED by ui_compiler.py  -- DO NOT EDIT")
    lines.append(f"// Source: ui/screens/{screen_name}.json")
    lines.append(f"// ============================================================")
    lines.append(f"#pragma once")
    lines.append(f"")
    lines.append(f"#include \"ui_types.h\"")
    lines.append(f"")
    lines.append(f"namespace {ns} {{")
    lines.append(f"")

    bg = data.get("layers", {}).get("bg", {})
    bg_id = bg.get("image_id", "")
    lines.append(f"    // Background")
    lines.append(f"    constexpr const char* BG_IMAGE_ID = {cpp_string(bg_id)};")
    lines.append(f"    constexpr int BG_SCROLL_X = {bg.get('scroll_x', 0)};")
    lines.append(f"    constexpr int BG_SCROLL_Y = {bg.get('scroll_y', 0)};")
    lines.append(f"")

    sprites = data.get("sprites", [])
    lines.append(f"    // Sprites")
    lines.append(f"    constexpr int SPRITE_COUNT = {len(sprites)};")
    if sprites:
        lines.append(f"    constexpr ui_types::SpriteEntry SPRITES[SPRITE_COUNT] = {{")
        for spr in sprites:
            lines.append(
                f"        {{ {cpp_string(spr.get('id',''))}, "
                f"{cpp_string(spr.get('image_id',''))}, "
                f"{spr.get('x', 0)}, {spr.get('y', 0)}, "
                f"{'true' if spr.get('visible', True) else 'false'} }},"
            )
        lines.append(f"    }};")
    else:
        lines.append(f"    constexpr ui_types::SpriteEntry* SPRITES = nullptr;")
    lines.append(f"")

    texts = data.get("texts", [])
    lines.append(f"    // Texts")
    lines.append(f"    constexpr int TEXT_COUNT = {len(texts)};")
    if texts:
        lines.append(f"    constexpr ui_types::TextEntry TEXTS[TEXT_COUNT] = {{")
        for t in texts:
            align = t.get("h_align", "center")
            lines.append(
                f"        {{ {cpp_string(t.get('id',''))}, "
                f"{cpp_string(t.get('text',''))}, "
                f"{t.get('x', 0)}, {t.get('y', 0)}, "
                f"{'true' if align == 'center' else 'false'}, "
                f"{'true' if t.get('blink', False) else 'false'}, "
                f"{t.get('blink_interval', 30)}, "
                f"{'true' if t.get('visible', True) else 'false'} }},"
            )
        lines.append(f"    }};")
    else:
        lines.append(f"    constexpr ui_types::TextEntry* TEXTS = nullptr;")
    lines.append(f"")

    lines.append(f"    constexpr ui_types::ScreenData SCREEN = {{")
    lines.append(f"        BG_IMAGE_ID, BG_SCROLL_X, BG_SCROLL_Y,")
    lines.append(f"        SPRITE_COUNT, SPRITES,")
    lines.append(f"        TEXT_COUNT, TEXTS")
    lines.append(f"    }};")
    lines.append(f"")
    lines.append(f"}} // namespace {ns}")
    lines.append(f"")

    return "\n".join(lines)


def main():
    if not os.path.isdir(SCREENS_DIR):
        print(f"[ui_compiler] Warning: screens dir not found: {SCREENS_DIR}", file=sys.stderr)
        return

    os.makedirs(INCLUDE_DIR, exist_ok=True)

    compiled = 0
    for fname in os.listdir(SCREENS_DIR):
        if not fname.endswith(".json"):
            continue
        json_path = os.path.join(SCREENS_DIR, fname)
        screen_name = fname[:-5]
        out_path = os.path.join(INCLUDE_DIR, f"ui_data_{screen_name}.h")

        cpp_src = compile_screen(json_path)

        existing = ""
        if os.path.exists(out_path):
            with open(out_path, "r", encoding="utf-8") as f:
                existing = f.read()

        if existing != cpp_src:
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(cpp_src)
            print(f"[ui_compiler] Generated: {out_path}")
        else:
            print(f"[ui_compiler] Up-to-date: {out_path}")

        compiled += 1

    print(f"[ui_compiler] Done: {compiled} screen(s) processed.")

if __name__ == "__main__":
    main()
