#!/usr/bin/env python3
"""
Generate audio_ids.h and audio_dispatch_*.gen.h from Asset/audio/audio_manifest.json.

Normally invoked at the end of ui_compiler.main() (same EXTTOOL prebuild pass as layout JSON → ui_data_*.h).
"""

from __future__ import annotations

import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPT_DIR not in sys.path:
    sys.path.insert(0, SCRIPT_DIR)

PROJECT_ROOT = os.path.dirname(os.path.dirname(SCRIPT_DIR))
sys.path.insert(0, os.path.join(PROJECT_ROOT, "src", "gameeditor"))

import audio_manifest_io as am

PROJECT_ROOT = os.path.dirname(os.path.dirname(SCRIPT_DIR))
OUT_DIR = os.path.join(PROJECT_ROOT, "src", "game", "include", "generated")


def _sorted_se(se_categories: list[str], se: list[am.SeAudioEntry]) -> list[am.SeAudioEntry]:
    cat_rank = {c: i for i, c in enumerate(se_categories)}
    return sorted(se, key=lambda e: (cat_rank[e.category], e.number, e.id))


def _cpp_enum_body_bgm(entries: list[am.AudioEntry]) -> str:
    if not entries:
        return ""
    return "".join(f"    {e.id},\n" for e in entries)


def _cpp_enum_body_se_category(categories: list[str]) -> str:
    if not categories:
        return ""
    lines = []
    for c in categories:
        tok = am.sanitize_cpp_token(c)
        lines.append(f"    {tok},\n")
    return "".join(lines)


def _cpp_enum_body_se(entries: list[am.SeAudioEntry]) -> str:
    if not entries:
        return ""
    lines = []
    for e in entries:
        name = am.se_cpp_enum_name(e.category, e.id)
        lines.append(f"    {name},\n")
    return "".join(lines)


def _bgm_dispatch_switch(entries: list[am.AudioEntry]) -> str:
    lines = []
    for e in entries:
        stem = os.path.splitext(os.path.basename(e.file))[0].lower()
        lines.append(f"        case BgmId::{e.id}: return bn::music_items::{stem};")
    return "\n".join(lines)

def _bgm_name_switch(entries: list[am.AudioEntry]) -> str:
    lines = []
    for e in entries:
        display = e.display_name if hasattr(e, 'display_name') and e.display_name else e.id
        lines.append(f'        case BgmId::{e.id}: return "{display}";')
    return "\n".join(lines)


def _se_dispatch_switch(entries: list[am.SeAudioEntry]) -> str:
    lines = []
    for e in entries:
        stem = os.path.splitext(os.path.basename(e.file))[0].lower()
        enum_name = am.se_cpp_enum_name(e.category, e.id)
        lines.append(f"        case SeId::{enum_name}: return bn::sound_items::{stem};")
    return "\n".join(lines)

def _se_name_switch(entries: list[am.SeAudioEntry]) -> str:
    lines = []
    for e in entries:
        enum_name = am.se_cpp_enum_name(e.category, e.id)
        display = e.display_name if hasattr(e, 'display_name') and e.display_name else e.id
        lines.append(f'        case SeId::{enum_name}: return "{display}";')
    return "\n".join(lines)


def write_audio_ids(
    bgm: list[am.AudioEntry],
    se_categories: list[str],
    se: list[am.SeAudioEntry],
) -> None:
    bgm_n = len(bgm)
    se_n = len(se)
    se_sorted = _sorted_se(se_categories, se)
    bgm_enum = _cpp_enum_body_bgm(bgm)
    se_cat_enum = _cpp_enum_body_se_category(se_categories)
    se_enum = _cpp_enum_body_se(se_sorted)

    content = f"""// Generated by src/tools/generate_audio_assets.py — do not edit.
#pragma once

#include <cstdint>

constexpr unsigned BN_GENERATED_BGM_COUNT = {bgm_n};
constexpr unsigned BN_GENERATED_SE_COUNT = {se_n};

enum class BgmId : uint8_t {{
{bgm_enum}    COUNT
}};

enum class SeCategory : uint8_t {{
{se_cat_enum}    COUNT
}};

enum class SeId : uint8_t {{
{se_enum}    COUNT
}};
"""
    path = os.path.join(OUT_DIR, "audio_ids.h")
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[generate_audio_assets] Wrote {path}")


def write_bgm_dispatch(bgm: list[am.AudioEntry]) -> None:
    path = os.path.join(OUT_DIR, "audio_dispatch_bgm.gen.h")
    if not bgm:
        txt = """// Generated by src/tools/generate_audio_assets.py — do not edit.
#pragma once

#include "audio_ids.h"
#include "bn_music_item.h"

namespace audio_dispatch {

[[nodiscard]] constexpr bool bgm_id_valid(BgmId id)
{
    return static_cast<unsigned>(id) < static_cast<unsigned>(BgmId::COUNT);
}

// No BGM assets in manifest; play_bgm is a no-op at runtime.
[[nodiscard]] inline bn::music_item bgm_item(BgmId)
{
    return bn::music_item(0);
}

[[nodiscard]] inline const char* bgm_name(BgmId)
{
    return "?";
}

} // namespace audio_dispatch
"""
    else:
        switch_body = _bgm_dispatch_switch(bgm)
        first_stem = os.path.splitext(os.path.basename(bgm[0].file))[0].lower()
        txt = f"""// Generated by src/tools/generate_audio_assets.py — do not edit.
#pragma once

#include "audio_ids.h"
#include "bn_assert.h"
#include "bn_music_item.h"
#include "bn_music_items.h"

namespace audio_dispatch {{

[[nodiscard]] constexpr bool bgm_id_valid(BgmId id)
{{
    return static_cast<unsigned>(id) < static_cast<unsigned>(BgmId::COUNT);
}}

[[nodiscard]] inline bn::music_item bgm_item(BgmId id)
{{
    switch (id) {{
{switch_body}
        default:
            BN_ASSERT(false);
            break;
    }}
    return bn::music_items::{first_stem};
}}

[[nodiscard]] inline const char* bgm_name(BgmId id)
{{
    switch (id) {{
{_bgm_name_switch(bgm)}
        default:
            return "?";
    }}
}}

}} // namespace audio_dispatch
"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(txt)
    print(f"[generate_audio_assets] Wrote {path}")


def write_se_dispatch(se: list[am.SeAudioEntry], se_categories: list[str]) -> None:
    path = os.path.join(OUT_DIR, "audio_dispatch_se.gen.h")
    se_sorted = _sorted_se(se_categories, se)
    if not se_sorted:
        txt = """// Generated by src/tools/generate_audio_assets.py — do not edit.
#pragma once

#include "audio_ids.h"
#include "bn_sound_item.h"

namespace audio_dispatch {

[[nodiscard]] constexpr bool se_id_valid(SeId id)
{
    return static_cast<unsigned>(id) < static_cast<unsigned>(SeId::COUNT);
}

[[nodiscard]] inline bn::sound_item se_item(SeId)
{
    return bn::sound_item(0);
}

[[nodiscard]] inline const char* se_name(SeId)
{
    return "?";
}

} // namespace audio_dispatch
"""
    else:
        switch_body = _se_dispatch_switch(se_sorted)
        first = se_sorted[0]
        first_stem = os.path.splitext(os.path.basename(first.file))[0].lower()
        txt = f"""// Generated by src/tools/generate_audio_assets.py — do not edit.
#pragma once

#include "audio_ids.h"
#include "bn_assert.h"
#include "bn_sound_item.h"
#include "bn_sound_items.h"

namespace audio_dispatch {{

[[nodiscard]] constexpr bool se_id_valid(SeId id)
{{
    return static_cast<unsigned>(id) < static_cast<unsigned>(SeId::COUNT);
}}

[[nodiscard]] inline bn::sound_item se_item(SeId id)
{{
    switch (id) {{
{switch_body}
        default:
            BN_ASSERT(false);
            break;
    }}
    return bn::sound_items::{first_stem};
}}

[[nodiscard]] inline const char* se_name(SeId id)
{{
    switch (id) {{
{_se_name_switch(se_sorted)}
        default:
            return "?";
    }}
}}

}} // namespace audio_dispatch
"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(txt)
    print(f"[generate_audio_assets] Wrote {path}")


def main() -> None:
    check_files = os.environ.get("SKIP_AUDIO_MANIFEST_FILE_CHECK") != "1"
    try:
        bgm, se_categories, se = am.validate_manifest(
            PROJECT_ROOT, check_files_exist=check_files
        )
    except am.ManifestError as e:
        print(f"[generate_audio_assets] ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    write_audio_ids(bgm, se_categories, se)
    write_bgm_dispatch(bgm)
    write_se_dispatch(se, se_categories)


if __name__ == "__main__":
    main()
