#!/usr/bin/env python3
"""
generate_sprite_anims.py
Reads Asset/fixdata/sprite_animations.json and generates:
  1. src/game/include/generated/sprite_anim_data.h   -- data structs + SpriteAnimId enum
  2. src/game/include/generated/sprite_anim_dispatch.gen.h -- SpriteAnimId -> bn::sprite_item switch
Also writes .json sidecar files next to each sprite BMP so Butano knows width/height.
"""
from __future__ import annotations
import json
import os
import re
import sys

SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(os.path.dirname(SCRIPT_DIR))
sys.path.insert(0, os.path.join(PROJECT_ROOT, "src", "gameeditor"))

MANIFEST_PATH = os.path.join(PROJECT_ROOT, "Asset", "fixdata", "sprite_animations.json")
OUT_DIR       = os.path.join(PROJECT_ROOT, "src", "game", "include", "generated")
SPRITES_DIR   = os.path.join(PROJECT_ROOT, "Asset", "graphics", "sprites")


def sanitize(s: str) -> str:
    tok = re.sub(r"[^A-Za-z0-9_]", "_", s)
    if tok and tok[0].isdigit():
        tok = "_" + tok
    return tok


def load_manifest() -> dict:
    if not os.path.exists(MANIFEST_PATH):
        return {"version": 1, "animations": []}
    with open(MANIFEST_PATH, encoding="utf-8") as f:
        return json.load(f)


def find_sprite_bmp(sprite_name: str) -> str | None:
    """Walk SPRITES_DIR to find sprite_name.bmp"""
    for root, _, files in os.walk(SPRITES_DIR):
        if f"{sprite_name}.bmp" in files:
            return os.path.join(root, f"{sprite_name}.bmp")
    return None


def write_sidecar_jsons(anims: list[dict]) -> None:
    """Write .json sidecars for each clip sprite so Butano knows height."""
    for anim in anims:
        for clip in anim.get("clips", []):
            sprite = clip.get("sprite", "")
            height = clip.get("height", 16)
            bmp_path = find_sprite_bmp(sprite)
            if not bmp_path:
                print(f"  [sprite_anims] WARNING: BMP not found for '{sprite}'")
                continue
            sidecar_path = bmp_path.replace(".bmp", ".json")
            existing = {}
            if os.path.exists(sidecar_path):
                with open(sidecar_path, encoding="utf-8") as f:
                    try:
                        existing = json.load(f)
                    except Exception:
                        existing = {}
            # Only write if height differs or no sidecar yet
            if existing.get("height") != height or "type" not in existing:
                data = {"type": "sprite", "height": height}
                with open(sidecar_path, "w", encoding="utf-8") as f:
                    json.dump(data, f, indent=2)
                print(f"  [sprite_anims] sidecar written: {os.path.basename(sidecar_path)} (h={height})")


def generate_anim_data_h(anims: list[dict]) -> str:
    lines = [
        "// AUTO GENERATED by generate_sprite_anims.py -- DO NOT EDIT",
        "#pragma once",
        "#include <cstdint>",
        '#include "generated/audio_ids.h"',
        "",
        "struct FdSpriteClip {",
        "    uint8_t frame_count;",
        "    uint8_t frame_duration;",
        "    uint8_t sprite_width;",
        "    uint8_t sprite_height;",
        "};",
        "",
        "struct FdSpriteAnim {",
        "    const char*         id;",
        "    uint8_t             clip_count;",
        "    const FdSpriteClip* clips;",
        "    int8_t              default_loop_count; // -1=infinite",
        "    SeId                se_id;              // SeId::COUNT = none",
        "};",
        "",
        "enum class SpriteAnimId : uint8_t {",
    ]
    for anim in anims:
        lines.append(f"    {sanitize(anim['id'])},")
    lines += ["    COUNT", "};", ""]

    # Clip arrays
    for anim in anims:
        tok = sanitize(anim["id"])
        clips = anim.get("clips", [])
        if clips:
            lines.append(f"static constexpr FdSpriteClip clips_{tok}[] = {{")
            for c in clips:
                fc = c.get("frame_count", 1)
                fd = c.get("frame_duration", 6)
                w  = c.get("width", 16)
                h  = c.get("height", 16)
                lines.append(f"    {{{fc}, {fd}, {w}, {h}}},")
            lines.append("};")

    # g_sprite_anims
    lines.append("")
    lines.append("static constexpr FdSpriteAnim g_sprite_anims[] = {")
    for anim in anims:
        tok  = sanitize(anim["id"])
        clips = anim.get("clips", [])
        clip_ptr  = f"clips_{tok}" if clips else "nullptr"
        loop_cnt  = anim.get("default_loop_count", 1)
        se_id_str = anim.get("se_id", "")
        se_val    = f"SeId::{se_id_str}" if se_id_str else "SeId::COUNT"
        lines.append(f'    {{ "{anim["id"]}", {len(clips)}, {clip_ptr}, {loop_cnt}, {se_val} }},')
    lines.append("};")
    lines.append(f"static constexpr uint8_t kSpriteAnimCount = {len(anims)};")
    return "\n".join(lines) + "\n"


def generate_dispatch_h(anims: list[dict]) -> str:
    lines = [
        "// AUTO GENERATED by generate_sprite_anims.py -- DO NOT EDIT",
        "#pragma once",
        '#include "generated/sprite_anim_data.h"',
        '#include "bn_sprite_item.h"',
        '#include "bn_sprite_items_spr_dummy.h"',
        "",
    ]
    # Include headers for each unique sprite
    seen: set[str] = set()
    for anim in anims:
        for clip in anim.get("clips", []):
            s = clip.get("sprite", "")
            if s and s not in seen:
                seen.add(s)
                lines.append(f'#include "bn_sprite_items_{s}.h"')
    lines.append("")

    lines += [
        "inline const bn::sprite_item& get_sprite_item_for_clip(",
        "    SpriteAnimId anim_id, int clip_idx)",
        "{",
        "    switch (anim_id) {",
    ]
    for anim in anims:
        tok   = sanitize(anim["id"])
        clips = anim.get("clips", [])
        if not clips:
            continue
        lines.append(f"        case SpriteAnimId::{tok}:")
        if len(clips) == 1:
            s = clips[0].get("sprite", "spr_dummy")
            lines.append(f"            return bn::sprite_items::{s};")
        else:
            lines.append("            switch (clip_idx) {")
            for i, c in enumerate(clips):
                s = c.get("sprite", "spr_dummy")
                lines.append(f"                case {i}: return bn::sprite_items::{s};")
            lines.append(f"                default: return bn::sprite_items::{clips[0].get('sprite','spr_dummy')};")
            lines.append("            }")
    lines += [
        "        default:",
        "            return bn::sprite_items::spr_dummy;",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    manifest = load_manifest()
    anims    = manifest.get("animations", [])
    os.makedirs(OUT_DIR, exist_ok=True)

    write_sidecar_jsons(anims)

    anim_data_path    = os.path.join(OUT_DIR, "sprite_anim_data.h")
    dispatch_path     = os.path.join(OUT_DIR, "sprite_anim_dispatch.gen.h")

    with open(anim_data_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(generate_anim_data_h(anims))
    print(f"  [sprite_anims] generated {anim_data_path}")

    with open(dispatch_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(generate_dispatch_h(anims))
    print(f"  [sprite_anims] generated {dispatch_path}")


if __name__ == "__main__":
    main()
